### ISSUE TITLE
Net and text problems

### ISSUE THREAD

**Issue by n1kub** [Sertyhopss/android-labs-http#1]
Commit messages are quite poor and `java.net.HttpURLConnection` is deprecated. 
By the way why don't you put .idea in .gitignore?

**Comment by Sertyhopss** [comment]
Thank you for your feedback! There is three different questions (literally one, but who cares?):

1. "Init commit" is the [commonly used](https://medium.com/genielab/git-for-beginners-flying-in-the-clouds-23cfa6fbc7fa) name for first commit in repository. First commit affects only `settings.gradle` because of my inattention. Thus, the direct initialization of the project is based on the second commit and I should have called it "Init commit" too, but in the name of Universal Justice I actually added "#2".

2. Can you prove this information? HTTPUrlConnection is an important part of Android SDK. Since Android API 22 Apache HttpClient is [deprecated and can no longer be used in any Android apps](https://developer.android.com/about/versions/lollipop/android-5.1#http). As I know, `java.net.HttpClient` class isn't included in Android SDK yet. Now HTTPUrlConnection is recommended class for network operations. 

3. I agree with you that it is mistake, I'll fix it later, thanks!

**Comment by n1kub** [comment]
> Thus, the direct initialization of the project is based on the second commit and I should have called it "Init commit" too

As far as I know this is already finished project. Don't you think that there sgould be more than just init commit?

> HTTPUrlConnection is an important part of Android SDK. 

That's it. You're absolutely right, it was wrong to say that it's deprecated. I just wanted to say, that you should follow common best practices and use some libraries to make code clear and more understandable.
If you want to use low-level API there is [`okHttp`](https://square.github.io/okhttp/), but for your purposes I'll recommed [`Volley`](https://developer.android.com/training/volley/simple) or [`Retrofit`](https://square.github.io/retrofit/)
